apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-deployment

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: player

  template:
    metadata:
      labels:
        app: player

    spec:
      containers:
      - name: p-app
        image: register_app:1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"